kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: github-deployment-controller
subjects:
- kind: ServiceAccount
  name: github-deployment-controller
  namespace: github-deployment-controller
roleRef:
  kind: ClusterRole
  name: github-deployment-controller
  apiGroup: rbac.authorization.k8s.io
